name: Byrdhouse
favicon: null
layout_spectrum: 0.16813804861158133
typography_spectrum: 0.4880807807203382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5066224047914147
  lightness: 0.6456353443209082
  saturation: 0.7361015016213059
  rhythmicContrast: 0.9214934231713414
purpose: []
