name: Byrdhouse
favicon: null
layout_spectrum: 0.50333
typography_spectrum: 0
title: Byrdhouse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f191b'
    - '#384635'
    - '#686f50'
    - '#9e9e7a'
    - '#dce0c7'
  brandStrength: 0
  lightness: 0.6456353443209082
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
